"""Tests for ilan.gist — Gist mirroring helpers and the async GistSyncer.

No test here touches the real GitHub API: the network calls
(``create_gist`` / ``post_comment``) are monkeypatched, so the suite exercises
the syncer's bookkeeping (gist creation, incremental comment posting, dedup,
error resilience) entirely offline.
"""

from __future__ import annotations

import email.message
import threading
import urllib.error
from pathlib import Path

import pytest

import ilan.gist as gist_mod
from ilan.gist import (
    GistSyncer,
    format_comment,
    gist_description,
    gist_enabled,
    github_token,
    initial_file,
)
from ilan.models import LogEntry, Task
from ilan.store import Store


# ── pure helpers ────────────────────────────────────────────────────────


class TestHelpers:
    def test_safe_filename(self) -> None:
        assert gist_mod._safe_filename("my task/1") == "my_task_1.md"
        assert gist_mod._safe_filename("clean-name_1.2") == "clean-name_1.2.md"

    def test_safe_filename_empty_fallback(self) -> None:
        assert gist_mod._safe_filename("///") == "conversation.md"

    def test_initial_file(self) -> None:
        filename, content = initial_file("task-abc")
        assert filename == "task-abc.md"
        # The title line carries the task name as inline code; it is kept in
        # sync on rename (see the rename tests below), so it never goes stale.
        assert content.startswith("# ilan task `task-abc`\n")
        assert "task-abc" in content

    def test_initial_file_links_to_parent_branch_comment(self) -> None:
        parent_url = (
            "https://gist.github.com/u/parent"
            "?permalink_comment_id=7#gistcomment-7"
        )
        filename, content = initial_file("child", parent_url)
        assert filename == "child.md"
        assert f"(<{parent_url}>)" in content
        assert "Messages inherited at that point are not repeated here" in content

    def test_gist_description_contains_task_name(self) -> None:
        assert gist_description("task-abc") == "ilan task (task-abc)"

    def test_format_comment_user(self) -> None:
        entry = LogEntry(role="user", content="hello **world**", timestamp="")
        out = format_comment(entry)
        assert out == "**User**\n\nhello **world**"

    def test_format_comment_assistant(self) -> None:
        entry = LogEntry(role="assistant", content="done", timestamp="")
        out = format_comment(entry)
        assert out == "**Assistant**\n\ndone"

    def test_format_comment_assistant_with_model(self) -> None:
        entry = LogEntry(
            role="assistant", content="done", timestamp="", model="claude-opus-4-8"
        )
        out = format_comment(entry)
        assert out == (
            "**Assistant**\n\ndone\n\n*(message is generated by claude-opus-4-8)*"
        )

    def test_format_comment_assistant_with_model_and_effort(self) -> None:
        entry = LogEntry(
            role="assistant", content="done", timestamp="",
            model="claude-opus-4-8", effort="xhigh",
        )
        out = format_comment(entry)
        assert out == (
            "**Assistant**\n\ndone\n\n"
            "*(message is generated by claude-opus-4-8, effort: xhigh)*"
        )

    def test_format_comment_assistant_with_model_effort_and_budget(self) -> None:
        entry = LogEntry(
            role="assistant", content="done", timestamp="",
            model="claude-opus-5", effort="xhigh", budget="Team",
        )
        out = format_comment(entry)
        assert out == (
            "**Assistant**\n\ndone\n\n"
            "*(message is generated by claude-opus-5, effort: xhigh, budget: Team)*"
        )

    def test_format_comment_budget_without_effort(self) -> None:
        entry = LogEntry(
            role="assistant", content="done", timestamp="",
            model="gpt-5.6-sol", budget="API",
        )
        out = format_comment(entry)
        assert out == (
            "**Assistant**\n\ndone\n\n"
            "*(message is generated by gpt-5.6-sol, budget: API)*"
        )

    def test_format_comment_cost_renders_last(self) -> None:
        entry = LogEntry(
            role="assistant", content="done", timestamp="",
            model="claude-opus-5", effort="xhigh", budget="API", cost_usd=1.2345,
        )
        out = format_comment(entry)
        assert out == (
            "**Assistant**\n\ndone\n\n"
            "*(message is generated by claude-opus-5, effort: xhigh, "
            "budget: API, cost: $1.23)*"
        )

    def test_format_comment_cost_without_effort(self) -> None:
        entry = LogEntry(
            role="assistant", content="done", timestamp="",
            model="claude-opus-5", budget="API", cost_usd=0.5,
        )
        out = format_comment(entry)
        assert out == (
            "**Assistant**\n\ndone\n\n"
            "*(message is generated by claude-opus-5, budget: API, cost: $0.50)*"
        )

    def test_format_comment_subscription_cost_is_withheld(self) -> None:
        """A plan's price is notional, so the Gist never shows it either."""
        entry = LogEntry(
            role="assistant", content="done", timestamp="",
            model="claude-opus-5", effort="xhigh", budget="Team", cost_usd=1.2345,
        )
        out = format_comment(entry)
        assert out == (
            "**Assistant**\n\ndone\n\n"
            "*(message is generated by claude-opus-5, effort: xhigh, budget: Team)*"
        )

    def test_format_comment_zero_cost_omits_it(self) -> None:
        """Codex reports no cost, which must not render as a bogus $0.00."""
        entry = LogEntry(
            role="assistant", content="done", timestamp="",
            model="gpt-5.6-sol", budget="API", cost_usd=0.0,
        )
        out = format_comment(entry)
        assert out == (
            "**Assistant**\n\ndone\n\n"
            "*(message is generated by gpt-5.6-sol, budget: API)*"
        )

    def test_format_comment_effort_without_model_omits_footer(self) -> None:
        """Effort alone (model detection missed) renders no attribution line."""
        entry = LogEntry(role="assistant", content="done", timestamp="", effort="xhigh")
        out = format_comment(entry)
        assert out == "**Assistant**\n\ndone"

    def test_format_comment_user_ignores_model(self) -> None:
        entry = LogEntry(
            role="user", content="hi", timestamp="", model="claude-opus-4-8"
        )
        out = format_comment(entry)
        assert out == "**User**\n\nhi"

    def test_format_comment_unknown_role(self) -> None:
        entry = LogEntry(role="system", content="x", timestamp="")
        out = format_comment(entry)
        assert out.startswith("**system**")

    def test_format_comment_truncates(self) -> None:
        big = "x" * (gist_mod._MAX_COMMENT_CHARS + 500)
        entry = LogEntry(role="user", content=big, timestamp="")
        out = format_comment(entry)
        assert "…[truncated]" in out
        assert len(out) < len(big) + 200

    def test_inline_math_converted(self) -> None:
        r"""``\(...\)`` becomes GitHub's backtick-inline math (which renders in
        gist comments; the raw LaTeX delimiters do not)."""
        entry = LogEntry(
            role="assistant", content=r"Here \(s_t\) is the state.", timestamp=""
        )
        out = format_comment(entry)
        assert "$`s_t`$" in out
        assert r"\(" not in out

    def test_inline_math_inner_whitespace_stripped(self) -> None:
        entry = LogEntry(role="assistant", content=r"see \( A_{i,t} = A_i \).", timestamp="")
        out = format_comment(entry)
        assert "$`A_{i,t} = A_i`$" in out

    def test_display_math_converted_to_math_fence(self) -> None:
        entry = LogEntry(
            role="assistant",
            content="Gradient:\n\n\\[\n\\nabla J = \\sum_t A_t\n\\]\n\nDone.",
            timestamp="",
        )
        out = format_comment(entry)
        assert "```math\n\\nabla J = \\sum_t A_t\n```" in out
        assert "\\[" not in out

    def test_math_inside_code_fence_untouched(self) -> None:
        content = "Escape it:\n\n```regex\n\\(foo\\) and \\[bar\\]\n```\n"
        entry = LogEntry(role="assistant", content=content, timestamp="")
        out = format_comment(entry)
        assert "\\(foo\\) and \\[bar\\]" in out
        assert "$`" not in out
        assert "```math" not in out

    def test_math_inside_inline_code_untouched(self) -> None:
        entry = LogEntry(
            role="assistant", content=r"Use `\(x\)` to match a paren.", timestamp=""
        )
        out = format_comment(entry)
        assert r"`\(x\)`" in out
        assert "$`" not in out

    def test_dollar_math_left_alone(self) -> None:
        """Math already in GitHub syntax passes through unchanged."""
        content = "Inline $x_1$ and display:\n\n$$\ny = x^2\n$$\n"
        entry = LogEntry(role="assistant", content=content, timestamp="")
        out = format_comment(entry)
        assert "$x_1$" in out
        assert "$$\ny = x^2\n$$" in out

    def test_unbalanced_delimiters_untouched(self) -> None:
        entry = LogEntry(role="assistant", content=r"A lone \( stays put.", timestamp="")
        out = format_comment(entry)
        assert r"\(" in out
        assert "$`" not in out

    def test_math_converted_in_user_messages_too(self) -> None:
        entry = LogEntry(role="user", content=r"Prove \(x^2 \ge 0\).", timestamp="")
        out = format_comment(entry)
        assert "$`x^2 \\ge 0`$" in out


# ── comment header timestamps ───────────────────────────────────────────


class TestCommentTimestamp:
    """The role header carries the message's own time, in the server's zone."""

    def _pin_zone(self, name: str) -> None:
        import ilan.config as cfg_mod

        cfg_mod.save({**cfg_mod.DEFAULTS, "time-zone": name})

    def test_user_header_carries_local_time(self, tmp_config: Path) -> None:
        self._pin_zone("US/Pacific")
        entry = LogEntry(role="user", content="hi", timestamp="2026-07-24T23:46:03+00:00")
        assert format_comment(entry) == "**User (2026-07-24, 16:46:03 PDT)**\n\nhi"

    def test_assistant_header_keeps_model_footer(self, tmp_config: Path) -> None:
        self._pin_zone("US/Pacific")
        entry = LogEntry(
            role="assistant", content="ok",
            timestamp="2026-07-24T23:46:09+00:00", model="claude-opus-4-7",
        )
        assert format_comment(entry) == (
            "**Assistant (2026-07-24, 16:46:09 PDT)**\n\nok\n\n"
            "*(message is generated by claude-opus-4-7)*"
        )

    def test_configured_zone_is_used(self, tmp_config: Path) -> None:
        self._pin_zone("Asia/Tokyo")
        entry = LogEntry(role="user", content="hi", timestamp="2026-07-24T23:46:03+00:00")
        assert format_comment(entry) == "**User (2026-07-25, 08:46:03 JST)**\n\nhi"

    def test_sub_second_precision_is_dropped(self, tmp_config: Path) -> None:
        self._pin_zone("US/Pacific")
        entry = LogEntry(
            role="user", content="hi", timestamp="2026-07-24T23:46:03.987654+00:00"
        )
        assert format_comment(entry) == "**User (2026-07-24, 16:46:03 PDT)**\n\nhi"

    @pytest.mark.parametrize("stamp", ["", "not-a-timestamp"])
    def test_unusable_stamp_falls_back_to_bare_label(self, stamp: str) -> None:
        """Old entries predating stored timestamps still render, just undated."""
        entry = LogEntry(role="user", content="hi", timestamp=stamp)
        assert format_comment(entry) == "**User**\n\nhi"

    def test_empty_stamp_does_not_read_config(self, monkeypatch: pytest.MonkeyPatch) -> None:
        """The common no-timestamp path must not hit the config file at all."""
        def boom() -> dict:
            raise AssertionError("config should not be loaded for an empty timestamp")

        monkeypatch.setattr(gist_mod.cfg, "load", boom)
        entry = LogEntry(role="user", content="hi", timestamp="")
        assert format_comment(entry) == "**User**\n\nhi"


# ── title rewrite (rename tracking) ─────────────────────────────────────


class TestUpdateGistTitle:
    def test_fetch_gist_filename(self, monkeypatch: pytest.MonkeyPatch) -> None:
        calls: list[tuple] = []

        def fake_api(method, path, token, payload=None):  # noqa: ANN001
            calls.append((method, path, payload))
            return {"files": {"my-task.md": {"content": "x"}}}

        monkeypatch.setattr(gist_mod, "_api_request", fake_api)
        assert gist_mod.fetch_gist_filename("tok", "gid9") == "my-task.md"
        assert calls == [("GET", "/gists/gid9", None)]

    def test_update_gist_title_patches_existing_file(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        calls: list[tuple] = []

        def fake_api(method, path, token, payload=None):  # noqa: ANN001
            calls.append((method, path, payload))
            if method == "GET":
                return {"files": {"old-name.md": {"content": "stale"}}}
            return {}

        monkeypatch.setattr(gist_mod, "_api_request", fake_api)
        gist_mod.update_gist_title("tok", "gid9", "new-name")

        assert calls[0] == ("GET", "/gists/gid9", None)
        method, path, payload = calls[1]
        assert method == "PATCH"
        assert path == "/gists/gid9"
        assert payload["description"] == "ilan task (new-name)"
        # The pre-existing filename is reused (file edited in place), and the
        # new content's title line tracks the new name.
        content = payload["files"]["old-name.md"]["content"]
        assert content.startswith("# ilan task `new-name`\n")

    def test_update_gist_title_still_updates_description_when_no_file(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        calls: list[tuple] = []

        def fake_api(method, path, token, payload=None):  # noqa: ANN001
            calls.append((method, path, payload))
            return {"files": {}}

        monkeypatch.setattr(gist_mod, "_api_request", fake_api)
        gist_mod.update_gist_title("tok", "gid9", "new-name")
        assert calls == [
            ("GET", "/gists/gid9", None),
            (
                "PATCH",
                "/gists/gid9",
                {"description": "ilan task (new-name)"},
            ),
        ]

    def test_update_gist_title_preserves_parent_comment_link(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        calls: list[tuple] = []

        def fake_api(method, path, token, payload=None):  # noqa: ANN001
            calls.append((method, path, payload))
            if method == "GET":
                return {"files": {"child.md": {"content": "stale"}}}
            return {}

        parent_url = "https://gist.github.com/u/parent#gistcomment-9"
        monkeypatch.setattr(gist_mod, "_api_request", fake_api)
        gist_mod.update_gist_title("tok", "gid9", "renamed-child", parent_url)

        content = calls[1][2]["files"]["child.md"]["content"]
        assert content.startswith("# ilan task `renamed-child`\n")
        assert f"(<{parent_url}>)" in content


# ── last-comment deep link ──────────────────────────────────────────────


class TestLastCommentUrl:
    HTML_URL = "https://gist.github.com/u/gid9"

    def test_no_comments_falls_back_to_gist_page(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        def fake_api(method, path, token, payload=None):  # noqa: ANN001
            return {"comments": 0}

        monkeypatch.setattr(gist_mod, "_api_request", fake_api)
        assert gist_mod.last_comment_url("tok", "gid9", self.HTML_URL) == self.HTML_URL

    def test_returns_permalink_to_last_comment(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        calls: list[tuple] = []

        def fake_api(method, path, token, payload=None):  # noqa: ANN001
            calls.append((method, path))
            if path == "/gists/gid9":
                return {"comments": 3}
            return [{"id": 4242}]

        monkeypatch.setattr(gist_mod, "_api_request", fake_api)
        url = gist_mod.last_comment_url("tok", "gid9", self.HTML_URL)
        assert url == (
            f"{self.HTML_URL}?permalink_comment_id=4242#gistcomment-4242"
        )
        # Pagination targets exactly the last comment (page = comment count).
        assert calls == [
            ("GET", "/gists/gid9"),
            ("GET", "/gists/gid9/comments?per_page=1&page=3"),
        ]

    def test_unexpected_comments_shape_falls_back(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        def fake_api(method, path, token, payload=None):  # noqa: ANN001
            if path == "/gists/gid9":
                return {"comments": 2}
            return {}

        monkeypatch.setattr(gist_mod, "_api_request", fake_api)
        assert gist_mod.last_comment_url("tok", "gid9", self.HTML_URL) == self.HTML_URL

    def test_comment_url_targets_exact_one_based_position(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        calls: list[tuple[str, str]] = []

        def fake_api(method, path, token, payload=None):  # noqa: ANN001
            calls.append((method, path))
            return [{"id": 1717}]

        monkeypatch.setattr(gist_mod, "_api_request", fake_api)
        url = gist_mod.comment_url("tok", "gid9", self.HTML_URL, 17)
        assert url == (
            f"{self.HTML_URL}?permalink_comment_id=1717#gistcomment-1717"
        )
        assert calls == [
            ("GET", "/gists/gid9/comments?per_page=1&page=17"),
        ]


# ── _api_request retry / backoff ────────────────────────────────────────


class _FakeResp:
    """Minimal context-manager stand-in for an ``http.client.HTTPResponse``."""

    def __init__(self, body: bytes = b"{}") -> None:
        self._body = body

    def __enter__(self) -> "_FakeResp":
        return self

    def __exit__(self, *exc: object) -> bool:
        return False

    def read(self) -> bytes:
        return self._body


def _http_error(code: int, retry_after: str | None = None) -> urllib.error.HTTPError:
    hdrs = email.message.Message()
    if retry_after is not None:
        hdrs["Retry-After"] = retry_after
    return urllib.error.HTTPError("https://x", code, "err", hdrs, None)


class TestApiRequestRetry:
    def test_retries_transient_urlerror_then_succeeds(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        calls = {"n": 0}

        def fake_urlopen(req, timeout=None):  # noqa: ANN001
            calls["n"] += 1
            if calls["n"] < 3:
                raise urllib.error.URLError("handshake timed out")
            return _FakeResp(b'{"ok": true}')

        sleeps: list[float] = []
        monkeypatch.setattr(gist_mod.urllib.request, "urlopen", fake_urlopen)
        monkeypatch.setattr(gist_mod.time, "sleep", lambda s: sleeps.append(s))

        out = gist_mod._api_request("GET", "/x", "tok")
        assert out == {"ok": True}
        assert calls["n"] == 3
        # Two failures → two backoff sleeps, growing exponentially.
        assert len(sleeps) == 2
        assert sleeps[1] > sleeps[0]

    def test_retries_timeout_error(self, monkeypatch: pytest.MonkeyPatch) -> None:
        calls = {"n": 0}

        def fake_urlopen(req, timeout=None):  # noqa: ANN001
            calls["n"] += 1
            if calls["n"] == 1:
                raise TimeoutError("ssl handshake")
            return _FakeResp(b"{}")

        monkeypatch.setattr(gist_mod.urllib.request, "urlopen", fake_urlopen)
        monkeypatch.setattr(gist_mod.time, "sleep", lambda s: None)
        assert gist_mod._api_request("POST", "/x", "tok", {"a": 1}) == {}
        assert calls["n"] == 2

    def test_retries_5xx(self, monkeypatch: pytest.MonkeyPatch) -> None:
        calls = {"n": 0}

        def fake_urlopen(req, timeout=None):  # noqa: ANN001
            calls["n"] += 1
            if calls["n"] < 2:
                raise _http_error(502)
            return _FakeResp(b"{}")

        monkeypatch.setattr(gist_mod.urllib.request, "urlopen", fake_urlopen)
        monkeypatch.setattr(gist_mod.time, "sleep", lambda s: None)
        gist_mod._api_request("GET", "/x", "tok")
        assert calls["n"] == 2

    def test_no_retry_on_non_retryable_status(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        calls = {"n": 0}

        def fake_urlopen(req, timeout=None):  # noqa: ANN001
            calls["n"] += 1
            raise _http_error(404)

        monkeypatch.setattr(gist_mod.urllib.request, "urlopen", fake_urlopen)
        monkeypatch.setattr(gist_mod.time, "sleep", lambda s: None)
        with pytest.raises(urllib.error.HTTPError):
            gist_mod._api_request("GET", "/x", "tok")
        assert calls["n"] == 1  # failed fast, no retry

    def test_gives_up_after_max_retries(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        calls = {"n": 0}

        def fake_urlopen(req, timeout=None):  # noqa: ANN001
            calls["n"] += 1
            raise urllib.error.URLError("down")

        monkeypatch.setattr(gist_mod.urllib.request, "urlopen", fake_urlopen)
        monkeypatch.setattr(gist_mod.time, "sleep", lambda s: None)
        with pytest.raises(urllib.error.URLError):
            gist_mod._api_request("GET", "/x", "tok")
        assert calls["n"] == gist_mod._MAX_RETRIES

    def test_honors_retry_after_header(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        calls = {"n": 0}

        def fake_urlopen(req, timeout=None):  # noqa: ANN001
            calls["n"] += 1
            if calls["n"] == 1:
                raise _http_error(429, retry_after="7")
            return _FakeResp(b"{}")

        sleeps: list[float] = []
        monkeypatch.setattr(gist_mod.urllib.request, "urlopen", fake_urlopen)
        monkeypatch.setattr(gist_mod.time, "sleep", lambda s: sleeps.append(s))
        gist_mod._api_request("POST", "/x", "tok", {"b": 2})
        assert sleeps == [7.0]

    def test_backoff_capped_for_network_errors(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        def fake_urlopen(req, timeout=None):  # noqa: ANN001
            raise urllib.error.URLError("down")

        sleeps: list[float] = []
        monkeypatch.setattr(gist_mod.urllib.request, "urlopen", fake_urlopen)
        monkeypatch.setattr(gist_mod.time, "sleep", lambda s: sleeps.append(s))
        with pytest.raises(urllib.error.URLError):
            gist_mod._api_request("GET", "/x", "tok")
        assert all(s <= gist_mod._MAX_BACKOFF_SECONDS for s in sleeps)

    def test_retry_after_is_not_capped(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """An explicit Retry-After larger than the backoff cap is honored in full."""
        calls = {"n": 0}
        big = gist_mod._MAX_BACKOFF_SECONDS + 30  # 60s, well above the 30s cap

        def fake_urlopen(req, timeout=None):  # noqa: ANN001
            calls["n"] += 1
            if calls["n"] == 1:
                raise _http_error(403, retry_after=str(int(big)))
            return _FakeResp(b"{}")

        sleeps: list[float] = []
        monkeypatch.setattr(gist_mod.urllib.request, "urlopen", fake_urlopen)
        monkeypatch.setattr(gist_mod.time, "sleep", lambda s: sleeps.append(s))
        gist_mod._api_request("POST", "/x", "tok", {"b": 2})
        assert sleeps == [big]  # uncapped

    def test_secondary_rate_limit_backs_off_hard(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """A header-less 403 (secondary limit) waits at least the long cooldown."""
        calls = {"n": 0}

        def fake_urlopen(req, timeout=None):  # noqa: ANN001
            calls["n"] += 1
            if calls["n"] == 1:
                raise _http_error(403)  # no Retry-After header
            return _FakeResp(b"{}")

        sleeps: list[float] = []
        monkeypatch.setattr(gist_mod.urllib.request, "urlopen", fake_urlopen)
        monkeypatch.setattr(gist_mod.time, "sleep", lambda s: sleeps.append(s))
        gist_mod._api_request("POST", "/x", "tok", {"b": 2})
        assert sleeps == [gist_mod._SECONDARY_LIMIT_BACKOFF_SECONDS]


# ── token / enabled ─────────────────────────────────────────────────────


class TestEnabled:
    def test_disabled_by_default(self, tmp_config: Path) -> None:
        assert github_token() == ""
        assert gist_enabled() is False

    def test_enabled_when_token_set(self, tmp_config: Path) -> None:
        import ilan.config as cfg

        c = cfg.load()
        c["github-token"] = "ghp_secret"
        cfg.save(c)
        assert github_token() == "ghp_secret"
        assert gist_enabled() is True


# ── GistSyncer ──────────────────────────────────────────────────────────


@pytest.fixture()
def store(tmp_workdir: Path) -> Store:
    return Store(tmp_workdir)


@pytest.fixture()
def syncer(store: Store) -> GistSyncer:
    return GistSyncer(store, threading.Lock())


class _FakeGitHub:
    """Records create_gist / post_comment calls in place of the real API."""

    def __init__(self) -> None:
        self.created: list[tuple[str, str]] = []
        self.created_content: list[str] = []
        self.comments: list[tuple[str, str]] = []
        self.title_updates: list[tuple[str, str]] = []
        self.title_update_parent_urls: list[str | None] = []
        self.comment_lookups: list[tuple[str, int]] = []
        self._counter = 0

    def create_gist(self, token, filename, content, description):  # noqa: ANN001
        self._counter += 1
        gid = f"gid-{self._counter}"
        self.created.append((filename, description))
        self.created_content.append(content)
        return gid, f"https://gist.github.com/u/{gid}"

    def post_comment(self, token, gist_id, body):  # noqa: ANN001
        self.comments.append((gist_id, body))

    def update_gist_title(  # noqa: ANN001
        self, token, gist_id, task_name, parent_comment_url=None
    ):
        self.title_updates.append((gist_id, task_name))
        self.title_update_parent_urls.append(parent_comment_url)

    def comment_url(  # noqa: ANN001
        self, token, gist_id, html_url, comment_number
    ):
        self.comment_lookups.append((gist_id, comment_number))
        return (
            f"{html_url}?permalink_comment_id={comment_number}"
            f"#gistcomment-{comment_number}"
        )


@pytest.fixture()
def fake_gh(monkeypatch: pytest.MonkeyPatch) -> _FakeGitHub:
    fake = _FakeGitHub()
    monkeypatch.setattr(gist_mod, "github_token", lambda: "tok")
    monkeypatch.setattr(gist_mod, "gist_enabled", lambda: True)
    monkeypatch.setattr(gist_mod, "create_gist", fake.create_gist)
    monkeypatch.setattr(gist_mod, "post_comment", fake.post_comment)
    monkeypatch.setattr(gist_mod, "update_gist_title", fake.update_gist_title)
    monkeypatch.setattr(gist_mod, "comment_url", fake.comment_url)
    # Don't actually wait out the inter-comment throttle in tests.
    monkeypatch.setattr(gist_mod.time, "sleep", lambda s: None)
    return fake


class TestSyncTask:
    def test_creates_gist_and_posts_all(
        self, store: Store, syncer: GistSyncer, fake_gh: _FakeGitHub
    ) -> None:
        store.put_task(Task(name="t1", prompt="p"))
        store.append_log("t1", "user", "hi")
        store.append_log("t1", "assistant", "yo")

        syncer.sync_task("t1")

        assert len(fake_gh.created) == 1
        assert len(fake_gh.comments) == 2
        task = store.get_task("t1")
        assert task is not None
        assert task.gist_id == "gid-1"
        assert task.gist_url.endswith("gid-1")
        assert task.gist_synced_count == 2
        # Creation records the name written into both title locations and needs
        # no separate title-update call.
        assert task.gist_title_name == "t1"
        assert task.gist_description == "ilan task (t1)"
        assert fake_gh.created == [("t1.md", "ilan task (t1)")]
        assert fake_gh.title_updates == []

    def test_rename_refreshes_title(
        self, store: Store, syncer: GistSyncer, fake_gh: _FakeGitHub
    ) -> None:
        store.put_task(Task(name="t1", prompt="p"))
        store.append_log("t1", "user", "hi")
        syncer.sync_task("t1")
        gid = store.get_task("t1").gist_id

        # Rename, then re-sync: both title locations must be rewritten to the
        # new name without recreating the gist or reposting comments.
        store.rename_task("t1", "t1-renamed")
        syncer.sync_task("t1-renamed")

        assert fake_gh.title_updates == [(gid, "t1-renamed")]
        assert len(fake_gh.created) == 1
        assert len(fake_gh.comments) == 1
        task = store.get_task("t1-renamed")
        assert task is not None
        assert task.gist_title_name == "t1-renamed"
        assert task.gist_description == "ilan task (t1-renamed)"

    def test_no_title_update_when_name_unchanged(
        self, store: Store, syncer: GistSyncer, fake_gh: _FakeGitHub
    ) -> None:
        store.put_task(Task(name="t1", prompt="p"))
        store.append_log("t1", "user", "hi")
        syncer.sync_task("t1")
        store.append_log("t1", "assistant", "yo")
        syncer.sync_task("t1")
        # Same name across both syncs → the title is never rewritten.
        assert fake_gh.title_updates == []

    def test_existing_gist_without_title_name_gets_refreshed(
        self, store: Store, syncer: GistSyncer, fake_gh: _FakeGitHub
    ) -> None:
        # A gist created before title-name tracking: gist_id is set but
        # gist_title_name is None, so the next sync backfills the title once.
        task = Task(name="legacy", prompt="p")
        task.gist_id = "gid-legacy"
        task.gist_url = "https://gist.github.com/u/gid-legacy"
        task.gist_synced_count = 1
        task.gist_title_name = None
        task.gist_description = None
        store.put_task(task)
        store.append_log("legacy", "user", "hi")

        syncer.sync_task("legacy")

        assert fake_gh.title_updates == [("gid-legacy", "legacy")]
        refreshed = store.get_task("legacy")
        assert refreshed is not None
        assert refreshed.gist_title_name == "legacy"
        assert refreshed.gist_description == "ilan task (legacy)"

    def test_existing_gist_with_backtick_description_gets_refreshed(
        self, store: Store, syncer: GistSyncer, fake_gh: _FakeGitHub
    ) -> None:
        # The previous description format used literal Markdown backticks,
        # which browser tabs do not render. The next sync replaces them.
        task = Task(name="legacy", prompt="p")
        task.gist_id = "gid-legacy"
        task.gist_url = "https://gist.github.com/u/gid-legacy"
        task.gist_synced_count = 1
        task.gist_title_name = "legacy"
        task.gist_description = "ilan task `legacy`"
        store.put_task(task)
        store.append_log("legacy", "user", "hi")

        syncer.sync_task("legacy")

        assert fake_gh.title_updates == [("gid-legacy", "legacy")]
        refreshed = store.get_task("legacy")
        assert refreshed is not None
        assert refreshed.gist_title_name == "legacy"
        assert refreshed.gist_description == "ilan task (legacy)"

    def test_throttles_between_comments(
        self, store: Store, syncer: GistSyncer, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """A backfill sleeps once between each pair of comments (not before the
        first), keeping bursts under GitHub's secondary rate limit."""
        monkeypatch.setattr(gist_mod, "github_token", lambda: "tok")
        monkeypatch.setattr(
            gist_mod, "create_gist", lambda *a, **k: ("gid-x", "https://g/gid-x")
        )
        monkeypatch.setattr(gist_mod, "post_comment", lambda *a, **k: None)
        sleeps: list[float] = []
        monkeypatch.setattr(gist_mod.time, "sleep", lambda s: sleeps.append(s))

        store.put_task(Task(name="t1", prompt="p"))
        for i in range(4):
            store.append_log("t1", "user", f"m{i}")
        syncer.sync_task("t1")

        # 4 comments → 3 inter-comment throttles of the configured duration.
        assert sleeps == [gist_mod._COMMENT_THROTTLE_SECONDS] * 3

    def test_incremental_only_posts_new(
        self, store: Store, syncer: GistSyncer, fake_gh: _FakeGitHub
    ) -> None:
        store.put_task(Task(name="t1", prompt="p"))
        store.append_log("t1", "user", "hi")
        syncer.sync_task("t1")
        assert len(fake_gh.comments) == 1

        store.append_log("t1", "assistant", "reply")
        syncer.sync_task("t1")
        # Only the new message is posted; gist is not recreated.
        assert len(fake_gh.created) == 1
        assert len(fake_gh.comments) == 2
        task = store.get_task("t1")
        assert task is not None
        assert task.gist_synced_count == 2

    def test_backfills_existing_history(
        self, store: Store, syncer: GistSyncer, fake_gh: _FakeGitHub
    ) -> None:
        # A pre-existing task with history but no gist yet: first sync mirrors
        # the ENTIRE conversation.
        store.put_task(Task(name="old", prompt="p"))
        for i in range(4):
            store.append_log("old", "user", f"m{i}")
        syncer.sync_task("old")
        assert len(fake_gh.created) == 1
        assert len(fake_gh.comments) == 4

    def test_branch_syncs_parent_then_only_posts_child_messages(
        self, store: Store, syncer: GistSyncer, fake_gh: _FakeGitHub
    ) -> None:
        parent = Task(name="parent", prompt="p", session_id="sid")
        store.put_task(parent)
        store.append_log("parent", "user", "parent question")
        store.append_log("parent", "assistant", "parent answer")
        store.branch_task(
            parent,
            "child",
            alias="aa",
            task_hash="deadbeef",
            now="2026-01-01T00:00:00+00:00",
        )
        store.append_log("child", "user", "child question")

        syncer.sync_task("child")

        # The parent is brought up to the branch cutoff first. The child gets
        # a fresh Gist but only its post-branch message becomes a comment.
        assert fake_gh.created == [
            ("parent.md", "ilan task (parent)"),
            ("child.md", "ilan task (child)"),
        ]
        assert len(fake_gh.comments) == 3
        assert [gist_id for gist_id, _ in fake_gh.comments] == [
            "gid-1",
            "gid-1",
            "gid-2",
        ]
        assert "child question" in fake_gh.comments[-1][1]
        assert fake_gh.comment_lookups == [("gid-1", 2)]

        parent_url = (
            "https://gist.github.com/u/gid-1"
            "?permalink_comment_id=2#gistcomment-2"
        )
        assert f"(<{parent_url}>)" in fake_gh.created_content[1]
        child = store.get_task("child")
        assert child is not None
        assert child.gist_branch_point == 2
        assert child.gist_synced_count == 3
        assert child.gist_parent_comment_url == parent_url

    def test_nested_branch_uses_parent_relative_comment_number(
        self, store: Store, syncer: GistSyncer, fake_gh: _FakeGitHub
    ) -> None:
        grand = Task(name="grand", prompt="p", session_id="grand-sid")
        store.put_task(grand)
        store.append_log("grand", "user", "g1")
        store.append_log("grand", "assistant", "g2")
        parent = store.branch_task(
            grand,
            "parent",
            alias="aa",
            task_hash="1111aaaa",
            now="2026-01-01T00:00:00+00:00",
        )
        store.append_log("parent", "user", "p1")
        store.append_log("parent", "assistant", "p2")
        parent = store.get_task("parent")
        assert parent is not None
        parent.gist_id = "gid-parent"
        parent.gist_url = "https://gist.github.com/u/gid-parent"
        parent.gist_synced_count = 4
        parent.gist_parent_comment_url = "https://gist.github.com/u/grand#history"
        parent.gist_title_name = "parent"
        parent.gist_description = "ilan task (parent)"
        store.put_task(parent)

        store.branch_task(
            parent,
            "child",
            alias="bb",
            task_hash="2222bbbb",
            now="2026-01-02T00:00:00+00:00",
        )
        store.append_log("child", "user", "c1")

        syncer.sync_task("child")

        # Parent's first two unified-log entries are represented by its own
        # parent link, so log cutoff 4 maps to comment 2 in the parent Gist.
        assert fake_gh.comment_lookups == [("gid-parent", 2)]
        assert len(fake_gh.comments) == 1
        assert "c1" in fake_gh.comments[0][1]

    def test_no_gist_when_no_entries(
        self, store: Store, syncer: GistSyncer, fake_gh: _FakeGitHub
    ) -> None:
        store.put_task(Task(name="empty", prompt="p"))
        syncer.sync_task("empty")
        assert fake_gh.created == []
        assert fake_gh.comments == []

    def test_missing_task_is_noop(
        self, syncer: GistSyncer, fake_gh: _FakeGitHub
    ) -> None:
        syncer.sync_task("ghost")
        assert fake_gh.created == []

    def test_disabled_no_token(
        self, store: Store, syncer: GistSyncer, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.setattr(gist_mod, "github_token", lambda: "")
        store.put_task(Task(name="t1", prompt="p"))
        store.append_log("t1", "user", "hi")
        syncer.sync_task("t1")
        task = store.get_task("t1")
        assert task is not None
        assert task.gist_id is None

    def test_partial_post_failure_advances_count(
        self, store: Store, syncer: GistSyncer, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """If posting fails mid-way, already-posted comments still count so a
        retry doesn't double-post them."""
        monkeypatch.setattr(gist_mod, "github_token", lambda: "tok")
        monkeypatch.setattr(gist_mod.time, "sleep", lambda s: None)
        monkeypatch.setattr(
            gist_mod, "create_gist", lambda *a, **k: ("gid-x", "https://g/gid-x")
        )
        calls = {"n": 0}

        def flaky_post(token, gist_id, body):  # noqa: ANN001
            calls["n"] += 1
            if calls["n"] == 2:
                raise RuntimeError("boom")

        monkeypatch.setattr(gist_mod, "post_comment", flaky_post)

        store.put_task(Task(name="t1", prompt="p"))
        store.append_log("t1", "user", "a")
        store.append_log("t1", "assistant", "b")
        store.append_log("t1", "user", "c")

        with pytest.raises(RuntimeError):
            syncer.sync_task("t1")

        task = store.get_task("t1")
        assert task is not None
        # First comment posted before the failure counts.
        assert task.gist_synced_count == 1
        assert task.gist_id == "gid-x"


class TestEnqueue:
    def test_enqueue_dedups(
        self, syncer: GistSyncer, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.setattr(gist_mod, "gist_enabled", lambda: True)
        syncer.enqueue("t1")
        syncer.enqueue("t1")
        assert syncer._queue.qsize() == 1

    def test_enqueue_noop_when_disabled(
        self, syncer: GistSyncer, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.setattr(gist_mod, "gist_enabled", lambda: False)
        syncer.enqueue("t1")
        assert syncer._queue.qsize() == 0

    def test_worker_processes_queue(
        self, store: Store, syncer: GistSyncer, fake_gh: _FakeGitHub
    ) -> None:
        store.put_task(Task(name="t1", prompt="p"))
        store.append_log("t1", "user", "hi")
        syncer.start()
        try:
            syncer.enqueue("t1")
            deadline = threading.Event()
            for _ in range(50):
                if store.get_task("t1").gist_id is not None:
                    break
                deadline.wait(0.05)
        finally:
            syncer.stop()
        task = store.get_task("t1")
        assert task is not None
        assert task.gist_id == "gid-1"

    def test_worker_survives_sync_error(
        self, store: Store, syncer: GistSyncer, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.setattr(gist_mod, "gist_enabled", lambda: True)

        def boom(name):  # noqa: ANN001
            raise RuntimeError("kaboom")

        monkeypatch.setattr(syncer, "sync_task", boom)
        syncer.start()
        try:
            syncer.enqueue("t1")
            threading.Event().wait(0.2)
            # Worker thread must still be alive after swallowing the error.
            assert syncer._thread is not None
            assert syncer._thread.is_alive()
        finally:
            syncer.stop()
