"""Produce a markdown summary of a task's conversation log.

The summary is generated by invoking ``claude -p`` with the prompt template
at ``prompts/summarize.md`` plus the task's log contents. The resulting
file lives alongside the log at ``<workdir>/logs/<task_name>.summary.md``
and a sidecar ``.summary.meta.json`` remembers the log hash so that
re-running ``ilan summarize`` on an unchanged task is a no-op (it just
re-opens the existing summary).
"""

from __future__ import annotations

import hashlib
import json
import os
import subprocess
from dataclasses import dataclass
from pathlib import Path

from ilan import config as cfg
from ilan.models import LogEntry
from ilan.store import Store

_PROMPT_FILE = Path(__file__).parent / "prompts" / "summarize.md"


@dataclass
class SummarizeResult:
    summary_path: Path
    reused: bool  # True if we skipped regeneration and reused the cached summary


def summary_path_for(log_path: Path) -> Path:
    return log_path.with_suffix(".summary.md")


def meta_path_for(log_path: Path) -> Path:
    return log_path.with_suffix(".summary.meta.json")


def log_hash(log_path: Path) -> str:
    """Content hash of the JSONL log file (empty string if it doesn't exist)."""
    if not log_path.exists():
        return ""
    h = hashlib.sha1()
    with open(log_path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _format_log(entries: list[LogEntry]) -> str:
    """Render the JSONL log as a human-readable transcript for the model."""
    parts: list[str] = []
    for i, e in enumerate(entries):
        label = "User" if e.role == "user" else "Assistant"
        header = f"### Message {i + 1} — {label} ({e.timestamp})"
        parts.append(f"{header}\n\n{e.content}")
    return "\n\n---\n\n".join(parts)


def _build_prompt(task_name: str, task_prompt: str, entries: list[LogEntry]) -> str:
    template = _PROMPT_FILE.read_text()
    log_text = _format_log(entries)
    return (
        f"{template}\n"
        f"\n"
        f"---\n"
        f"\n"
        f"# Task metadata\n"
        f"\n"
        f"- Name: `{task_name}`\n"
        f"\n"
        f"## Original task prompt\n"
        f"\n"
        f"{task_prompt}\n"
        f"\n"
        f"## Conversation log\n"
        f"\n"
        f"{log_text}\n"
    )


def _run_claude(prompt: str, model: str, effort: str) -> str:
    """Invoke ``claude -p`` and return the text response.

    Uses ``--output-format json`` and pulls the ``result`` field so we don't
    accidentally capture Claude's own status line or prompt-cache chatter.
    """
    cmd = [
        "claude", "-p", prompt,
        "--model", model,
        "--effort", effort,
        "--dangerously-skip-permissions",
        "--output-format", "json",
    ]

    env = os.environ.copy()
    api_key = str(cfg.load().get("api-key", "")).strip()
    if api_key:
        env["ANTHROPIC_API_KEY"] = api_key

    proc = subprocess.run(cmd, capture_output=True, text=True, env=env, timeout=900)
    if proc.returncode != 0:
        stderr = proc.stderr.strip() or proc.stdout.strip()
        raise RuntimeError(f"claude -p failed (exit {proc.returncode}): {stderr}")

    try:
        payload = json.loads(proc.stdout)
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"claude -p returned non-JSON output: {exc}") from exc

    if payload.get("is_error"):
        raise RuntimeError(f"claude -p reported an error: {payload.get('result', '')}")

    result = payload.get("result", "").strip()
    if not result:
        raise RuntimeError("claude -p returned an empty result")
    return result


def summarize(task_name_or_alias: str) -> SummarizeResult:
    """Produce (or reuse) the summary for a task.

    Returns the path to the summary file, plus a flag indicating whether the
    cached copy was reused. Raises ``ValueError`` / ``RuntimeError`` on
    failure so callers can render a single consistent error path.
    """
    store = Store(cfg.get_workdir())
    task = store.get_task_by_name_or_alias(task_name_or_alias)
    if task is None:
        raise ValueError(f"Task {task_name_or_alias!r} not found")

    log_path = store.log_path(task.name)
    entries = store.read_logs(task.name)
    if not entries:
        raise ValueError(f"Task {task.name!r} has no log entries yet")

    summary_path = summary_path_for(log_path)
    meta_path = meta_path_for(log_path)
    current_hash = log_hash(log_path)

    if summary_path.exists() and meta_path.exists():
        try:
            with open(meta_path) as f:
                meta = json.load(f)
            if meta.get("log_hash") == current_hash:
                return SummarizeResult(summary_path=summary_path, reused=True)
        except (json.JSONDecodeError, OSError):
            pass  # fall through and regenerate

    conf = cfg.load()
    model = str(conf.get("summarize-model", "sonnet"))
    effort = str(conf.get("summarize-effort", "medium"))

    prompt = _build_prompt(task.name, task.prompt, entries)
    summary_text = _run_claude(prompt, model=model, effort=effort)

    summary_path.write_text(summary_text + ("\n" if not summary_text.endswith("\n") else ""))
    with open(meta_path, "w") as f:
        json.dump(
            {"log_hash": current_hash, "model": model, "effort": effort},
            f,
            indent=2,
        )
    return SummarizeResult(summary_path=summary_path, reused=False)
